name: robokru
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Recommended dependencies for drift
  drift: ^2.7.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.2

  # Riverpod dependencies
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.3.6

  # Navigation
  go_router: ^7.0.0

  # Data Types
  uuid: ^3.0.7

  protobuf: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  custom_lint: ^0.3.4
  riverpod_lint: ^1.3.1

  build_runner: ^2.3.3

  drift_dev: ^2.7.0
  protoc_builder: ^0.3.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
