name: robokru
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'
null_safety: true
version: "2.0.0"
build_number: 1

environment:
  sdk: '>=3.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Recommended dependencies for drift
  drift: ^2.8.0
  sqlite3: ^1.11.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.2

  # Riverpod dependencies
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.3.6

  # Navigation
  go_router: ^7.0.0

  # Data Types
  uuid: ^3.0.7

  protobuf: ^2.1.0
  shared_preferences: ^2.1.1
  collection: ^1.17.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.1
  drift_dev: ^2.8.0

  build_runner: ^2.4.4
  build_web_compilers: ^4.0.3

  protoc_builder: ^0.3.1
  freezed: ^2.3.4
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
